[package]
name = "kittysplit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
structopt = "0.3.26"
tempfile = "3.3.0"
regex = "1.3.3"
indoc = "1.0.7"
